# Generated by Django 3.2.12 on 2023-05-26 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
